# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 91ce6bd9b98ba656e814474f227ee12c437686095f33b19cacfaa1bc6f492204488099e401ca89f56f06db4303f7da65b833997d59fc1c079b50e1bac512626d

test:
  secret_key_base: fb2ef7091667bb837abf1a17cd53b4b90b8bef1337e45aa06ec4a9ce947fd149de7f9c85ad32dd8716a2ff1b4af9b3bceb6cc0dd73b51283d1b2d92b91e08b13

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
